repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt
        language: system
        types: [ rust ]
        pass_filenames: false
        args: [ "--" ]  # 注意空格！前面要有空格

      - id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        pass_filenames: false
        always_run: true
        args: [ "--fix", "--allow-dirty", "--", "-D", "warnings" ]  # 注意空格！

      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        pass_filenames: false
        always_run: true